# Generated by Django 5.2.6 on 2025-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Processando', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_url', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
